### ISSUE TITLE
API login

### ISSUE THREAD

**Issue by SnAFKe** [kdeenkhoorn/dns_cpaneldns#1]
What is the API you're asking when you using this plugin.

The first time give me this error

> You don't specify cpaneldns api id and password or api web interface yet.

Ok, i try to create API via WHM.

> Invalid CPANELDNS_AUTH_ID or CPANELDNS_AUTH_PASSWORD. Please check your login credentials.

Not good.

Lets try again.

Using my user login.

> Invalid CPANELDNS_AUTH_ID or CPANELDNS_AUTH_PASSWORD. Please check your login credentials.

So i'm not sure what auth is looking for.

**Comment by kdeenkhoorn** [comment]
This script is a plugin for acme.sh  found in te repository https://github.com/Neilpang/acme.sh and has to be treated as such. In general, before you start issueing a new certificate you have to set a few variables for the plugin once. These variables can be found in the first lines of the script.

So before you start using acme.sh with this plugin you have to set the following variables once and only on first use.

export CPANELDNS_AUTH_ID="xxxxxxxx"
export CPANELDNS_AUTH_PASSWORD="yyyyyyyyyyy"
export CPANELDNS_API="https://zzz.zzz.zzz:2083/"

Copy this dns_cpaneldns script in a subdirectory below acme.sh with the name 'dnsapi' and then you can execute:

acme.sh --issue --dns dns_cpaneldns -d example.com -d www.example.com

These one-time set variables will be saved for later use in the configuration of acme.sh.
See: https://github.com/Neilpang/acme.sh/tree/master/dnsapi for reference.

Have fun!

**Comment by kdeenkhoorn** [comment]
To be clear:
CPANELDNS_AUTH_ID = Your CPanel's User ID
CPANELDNS_AUTH_PASSWORD = Your CPanels User ID password
CPANELDNS_API = Your Cpanels web adress including portnumber, mostly 2083

**Comment by SnAFKe** [comment]
I already do that and not accept my login.

I debug it and give me this error.

> response='{"cpanelresult":{"apiversion":"2","error":"Access denied","data":{"reason":"Access denied","result":"0"},"type":"text"}}

I already tested to login my cPanel with same login and i'm able to login.

Now i reset my login and try again now seems working and issue!!!.

No sure why my previous login not working.

Other issue because of my problem and try over and over i got limited by Let's Encrypt . Cool because of that y try to use staging but not working.

> ./acme.sh --staging --dns dns_cpaneldns -d domain.com

**Comment by kdeenkhoorn** [comment]
Hi,

You can check in CPanel during the 120 seconds wait if the records are created. But good to hear it works.

It seems you have to wait 7 days if you have tried to many times for a letsencrypt certificate. Maybe you can try to remove the .acme.sh directory entirely and start allover.

What the option --staging does i don't know. 
Maybe the developer of the acme script can answer that. I'm not that familair with acme.sh to be able to answer that question.

**Comment by kdeenkhoorn** [comment]
No response to latest message, assuming problem is solved, Closing issue.
