### ISSUE TITLE
sed: illegal option -- r

### ISSUE THREAD

**Issue by biovolt** [kdeenkhoorn/dns_cpaneldns#2]
Thank you for your valuable contribution !!!!!!

It gets stuck in this mode while cleaning up.
running on an Mac 10.15.5

[Tue Jul 16 14:14:06 SAST 2019] Success
[Tue Jul 16 14:14:06 SAST 2019] Removing DNS records.
[Tue Jul 16 14:14:06 SAST 2019] Removing txt: ********-fwBr3qKlUtfRIaSiy_eeCVE for domain: _acme-challenge.*******.com
[Tue Jul 16 14:14:06 SAST 2019] Using CPanelDNS
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
[Tue Jul 16 14:14:08 SAST 2019] Removing record ID:
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
[Tue Jul 16 14:14:08 SAST 2019] Removing record ID:
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

**Comment by kdeenkhoorn** [comment]
Oke, this is going to be a bit difficult,. There seems to go something wrong during the statement: sed -re 's/^\"line\"\:\"([0-9]+)\"$/\1/g', this command is using extended regular expressions (-r).
It seems MAC does not have the option '-r' for sed. But i have no MAC, and not going to have one in the near future also ...

Have to dive into it if i can find an other way of solving this.

**Comment by biovolt** [comment]
Like you said. sed in mac and gnu are different and mac does not have all the options

Workaround : 
I installed gnu-sed and changed the sed in the file to gsed.
`brew install gnu-sed`
This solved it for me but all users won't be able to do this

**Comment by kdeenkhoorn** [comment]
I'm not familiar with MAC but what you can possibly do is before starting the acme.sh script first define an alias in your shell for sed to point to gnu-sed so you don't have to alter the script.
Also you can put gnu-sed earlier in your path in combination with an symlink.

Possible solution can be found on page: https://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-x

**Comment by kdeenkhoorn** [comment]
Closing issue because there is a workaround is available.

Workaround:
I installed gnu-sed and changed the sed in the file to gsed.
brew install gnu-sed
